### ISSUE TITLE
bigger lpc_order leads to bad pred results?

### ISSUE THREAD

**Issue by BridgetteSong** [zzw922cn/LPC_for_TTS#2]
When I use lpc_order=16, pred_wav contains much noise.

**Comment by zzw922cn** [comment]
yes，it may contains some noise, however, when used in LPCNet, such prediction error can be remedied.

**Comment by BridgetteSong** [comment]
I accidentally found, are you one of the authers of [https://arxiv.org/abs/2005.05551](url)?
Will multi-band be supported in the feature?
Thanks

**Comment by zzw922cn** [comment]
@BridgetteSong hi，If you want to know how to use multi-band, you can refer to TensorFlowTTS project through github. In addition, I am also interested in the full implementation of multi-band algorithm in python. Would you like to work with me to finish it? I used to have some questions about this algorithm and I didn't finish it yet.

**Comment by BridgetteSong** [comment]
I referred to the **MB-MelGAN**, and I think this end2end method is easier than the **FeatherWave** as it don't need calculate the prediction. I have read the FeatherWave paper several times, I think
1.  It needs a **_Multi-band Linear Prediction_**, and I don't know how to **_extract lpcs of each sub frequency band from the corresponding frequency bins of mel-spectrogram frame_** correctly.
2. After having the multi-band linear predition, the neural network part is an easier task to implement.
3. If you want a full implementation of multi-band algorithm in python, I think many signal processes should be wrote by Python. And  it may be slower than C code, and some accelerated operations for the sparse matrices also need to be reconsidered. 

PS, I have a weak signal process foundation to help you, and if you need my help, I can do some neural network jobs.

**Comment by zzw922cn** [comment]
@BridgetteSong hi, as for multi-band linear prediction, we can just change the target of LPCNet from one raw audio signal into four sub-band audio signals. The process of estimating LPCs from mel-spectrogram keeps the same as original LPCNet.

**Comment by zzw922cn** [comment]
@BridgetteSong As for sub-band signal decomposition algorithm, I want to implement the Kaiser window method, which is much more efficient.

**Comment by Kristopher-Chen** [comment]
> yes，it may contains some noise, however, when used in LPCNet, such prediction error can be remedied.

hi， did noise mean clips like this?
![image](https://user-images.githubusercontent.com/38187438/165278411-68b0844a-395a-4a0e-a05f-35e7e94c3150.png)
